// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct MatrixDimensions
{
    uint width;
    uint height;
};

//Weights
RWStructuredBuffer<MatrixDimensions> matrixDim;

RWStructuredBuffer<double> matrixVals;

RWStructuredBuffer<double> transposedMatrix;

[numthreads(1,1,1)]
void CSMain(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint row = DispatchThreadID.y;
    uint col = DispatchThreadID.x;

    transposedMatrix[col * matrixDim[0].height + row] = matrixVals[row * matrixDim[0].width + col];
}
